services:
  web:
    build: .
    container_name: monSuperServerApache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - SUPER_ENVIRONEMENT_VARIABLE=Mon Super Site
    depends_on:
      - mysql
  mysql:
    image: mariadb
    container_name: monSuperServerMariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
  phpmyadmin:
    image: phpmyadmin
    container_name: monSuperServerPHPMyAdmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql